In [2]:
import numpy
numpy.__version__


'1.22.2'

In [4]:
import numpy as np
x = [1, 2 ,'3',4.3, True]

In [6]:
x = [1,2, 3.4, 4, '5']
y = np.array(x)
print(y)

['1' '2' '3.4' '4' '5']


In [7]:
import numpy as np
import time 


In [31]:
#time complexity
start = time.time()
for i,j in zip(list(range(10000)),list(range(10000))):
               z = i ** j
end = time.time()
print(f'time consumed is {end -start}')         


time consumed is 8.56526255607605


In [32]:
start = time.time()
for i,j in zip(np.array(list(range(10000))),np.array (list(range(10000)))):
               z = i ** j
end = time.time()
print(f'time consumed is {end -start}') 

time consumed is 0.018309354782104492


In [33]:
x = np.array ([1,2,3,4,5,6])
x *2 

array([ 2,  4,  6,  8, 10, 12])

In [34]:
x = [1,2,3,4,5]
x*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [35]:
np.array([1,2,4]) * np .array ([3,4,5])

array([ 3,  8, 20])

In [44]:
x = np.array([1,2,3,4,5])
print(x.shape) # dimention known by shape.
print(x.ndim) # give me the dimension of tensor

(5,)
1


In [52]:
x = np.arange(1,10) #
y = x.reshape(3,3) #
print (x)
print (y)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
np.random.normal(0,1, 10000)# mean =0,sd = 1, samples =10000

array([ 1.97691348,  0.61409423, -0.52664337, ...,  0.33807609,
        0.99878841,  0.4842312 ])

In [1]:
#slicing in num py

In [3]:
import numpy as np 
x = np.random.rand(4,5)
x

array([[0.42976316, 0.46058484, 0.47324188, 0.17433845, 0.6781373 ],
       [0.43973312, 0.88469431, 0.70443817, 0.65117628, 0.81860339],
       [0.19729652, 0.30939308, 0.87425979, 0.47518139, 0.4237785 ],
       [0.33078485, 0.64974976, 0.30972791, 0.21363898, 0.54217343]])

In [4]:
x[2:,3:]

array([[0.47518139, 0.4237785 ],
       [0.21363898, 0.54217343]])

In [6]:
import numpy as np 
np.random.seed(42)
x = np.random.rand(2,4,3,2)
x

array([[[[0.37454012, 0.95071431],
         [0.73199394, 0.59865848],
         [0.15601864, 0.15599452]],

        [[0.05808361, 0.86617615],
         [0.60111501, 0.70807258],
         [0.02058449, 0.96990985]],

        [[0.83244264, 0.21233911],
         [0.18182497, 0.18340451],
         [0.30424224, 0.52475643]],

        [[0.43194502, 0.29122914],
         [0.61185289, 0.13949386],
         [0.29214465, 0.36636184]]],


       [[[0.45606998, 0.78517596],
         [0.19967378, 0.51423444],
         [0.59241457, 0.04645041]],

        [[0.60754485, 0.17052412],
         [0.06505159, 0.94888554],
         [0.96563203, 0.80839735]],

        [[0.30461377, 0.09767211],
         [0.68423303, 0.44015249],
         [0.12203823, 0.49517691]],

        [[0.03438852, 0.9093204 ],
         [0.25877998, 0.66252228],
         [0.31171108, 0.52006802]]]])

In [9]:
x[0,2,:,1]

array([0.21233911, 0.18340451, 0.52475643])

In [68]:
Y = np.random.normal(20,5,(4,2,3,3))
Y

array([[[[18.72589366, 19.25061017, 22.6388238 ],
         [24.16611939, 13.36730492, 18.19054514],
         [19.65205089, 22.42657998, 16.13666429]],

        [[19.55389412, 20.14991817, 16.47764948],
         [16.35842425, 20.49372889, 19.34827427],
         [22.5023876 , 14.7337064 , 18.24659236]]],


       [[[18.85391974, 24.06931954, 15.29793113],
         [21.17326003, 21.26377754, 28.23198621],
         [14.96455318, 16.71383341, 15.31322159]],

        [[11.65110414, 28.82343467, 13.79249385],
         [15.91847295, 26.57883254, 11.23446477],
         [23.78175785, 12.93487827, 26.23347368]]],


       [[[ 9.15061156, 11.23265292, 17.27538883],
         [24.85911345, 19.84520875, 18.32142464],
         [26.73022104, 30.77619769, 23.36128642]],

        [[16.88572748, 17.90928483, 13.5577631 ],
         [20.50408711, 11.85203507, 22.75931828],
         [30.02787023, 23.5879579 , 17.6542614 ]]],


       [[[22.63468706, 28.10266723, 27.85247318],
         [14.98121054, 22.551481

In [21]:
X= np.random.randint(0,100,(5,1,2,2))
X

array([[[[85, 33],
         [ 7, 39]]],


       [[[82, 41],
         [40,  5]]],


       [[[51, 25],
         [63, 97]]],


       [[[58, 55],
         [58, 69]]],


       [[[32, 52],
         [21, 20]]]])

In [39]:
X[2,:,0,:]

array([[51, 25]])

In [41]:
X[3,:,1,:]


array([[63, 97]])

In [42]:
X[2,:,1,:]

array([[63, 97]])

In [43]:
X[4,:,0,:]

array([[32, 52]])

In [47]:
x =np.array((1,2,3,4,5,6))
x
x.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [48]:
y =np.array((1,2,3,4,5,6))
y
y[np.newaxis,:,np.newaxis]  # new axis creats an axis #vector to matrix

array([[[1],
        [2],
        [3],
        [4],
        [5],
        [6]]])

In [53]:
u = np.random.randn(3, 3)
u

array([[ 1.1063291 ,  0.77163815, -0.72333908],
       [ 2.43384808, -1.77024319, -1.03262907],
       [ 0.16972928,  0.08939392,  0.48804408]])

In [54]:
u.flatten('F')

array([ 1.1063291 ,  2.43384808,  0.16972928,  0.77163815, -1.77024319,
        0.08939392, -0.72333908, -1.03262907,  0.48804408])

In [55]:
u.flatten('C')

array([ 1.1063291 ,  0.77163815, -0.72333908,  2.43384808, -1.77024319,
       -1.03262907,  0.16972928,  0.08939392,  0.48804408])

In [61]:
x = np.random.randn(3,2)
y = np.random.randn(2,4)
np.matmul(x,y)


array([[-0.5473925 ,  0.89116038,  1.52174108, -3.45912702],
       [-0.25077475,  0.22245026, -0.44567248, -0.10242486],
       [-0.30261052,  0.40580059,  0.30707786, -1.21943338]])

In [66]:
x = np.random.randn(3,)
y = np.random.randn(1,4)
np.matmul(x[:,np.newaxis],y)


array([[ 1.2518098 ,  1.94303788, -0.67130103, -0.64528825],
       [ 0.33334234,  0.51740831, -0.17875963, -0.17183273],
       [-0.28814786, -0.44725821,  0.15452344,  0.14853569]])

In [69]:
Y = np.random.normal(20,5,(4,2,3,3))
Y

array([[[[11.23213141, 30.40657328, 18.47723181],
         [20.47660403, 20.89518398, 23.03783432],
         [12.40410009, 19.97331765, 16.70615587]],

        [[11.55221387, 24.935611  , 18.23913508],
         [21.21260213, 20.89922709, 18.32573864],
         [29.87513677, 19.76367674, 12.21023841]]],


       [[[17.9980932 , 22.4986881 , 22.66297555],
         [14.56109532, 24.64741254, 11.18566536],
         [25.72067601, 13.40326055, 18.8687739 ]],

        [[25.32284339, 20.59802834, 24.08349259],
         [23.0933098 , 26.43134307, 25.31104925],
         [17.73127846, 23.16470817, 12.36724069]]],


       [[[19.71047546, 24.09242367, 20.66923827],
         [22.23319866, 18.93363812, 25.64534719],
         [19.59792113, 17.67274909, 24.43258706]],

        [[12.97420039, 22.50516672, 14.78757563],
         [26.38963415, 18.69486373, 20.6749236 ],
         [22.06285198, 10.35157702, 16.74707579]]],


       [[[25.21772955, 24.33882512, 21.41516103],
         [13.25268214, 22.927517

In [76]:
Y[3,0,:,0]

array([25.21772955, 13.25268214, 20.23508607])

In [75]:
Y[0,1,:,1]

array([24.935611  , 20.89922709, 19.76367674])

In [88]:
Y = np.random.normal(20,5,(2,2,3,4))
Y

array([[[[24.96344269, 22.72908587, 15.80059552, 17.17357612],
         [17.9464567 , 16.68643114,  9.85163066, 23.8179555 ],
         [26.28529978, 12.40775528, 26.21926466, 19.48488399]],

        [[26.12566174, 20.18975218, 20.67772296, 21.86217323],
         [16.04966837, 25.97337072, 14.39309681, 17.98966628],
         [22.62132339, 17.4540238 , 23.8876562 , 26.87933087]]],


       [[[25.06273001, 10.31942343, 20.62923485, 25.14341305],
         [13.41625577, 23.61805294, 23.33730391, 13.93955054],
         [24.17116333, 21.36348897, 23.25190894, 15.16843807]],

        [[20.75068058, 11.47560723,  8.61504396, 20.70414213],
         [25.50298803, 21.26468407, 19.68276968, 19.0623294 ],
         [15.28717304, 18.89069548, 22.10842234, 17.82388884]]]])

In [90]:
Y[1,1,:,2]

array([ 8.61504396, 19.68276968, 22.10842234])